//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.08 at 04:43:13 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://karthifairhawn.in/emp", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package in.karthifairhawn.emp;
